"""The publisher's real wire output, accepted by this consumer.

Both sides of this contract are validated against exact key sets, in different
repositories, in different languages. When they drifted apart nothing failed
until a deploy window: the publisher published happily and every message was
rejected here. These goldens are generated by the publisher itself; this test
proves we still accept what it actually sends.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import unittest
from datetime import datetime, timezone
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[1]
MODULE_PATH = REPOSITORY / "custom_components" / "my_lg" / "local_provider.py"
GOLDEN_PATH = Path(__file__).resolve().parent / "golden-publications.v1.json"
SIBLING_GOLDEN = (
    REPOSITORY.parent / "lg_rethink_local" / "local" / "semantic" / "golden-publications.v1.json"
)

SPEC = importlib.util.spec_from_file_location("my_lg_local_provider_golden", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
local = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = local
SPEC.loader.exec_module(local)

NOW = datetime(2026, 8, 13, 2, 0, tzinfo=timezone.utc)


class GoldenPublicationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.golden = json.loads(GOLDEN_PATH.read_text(encoding="utf8"))
        _revision, profiles, _digest = local.load_local_semantic_profile_catalogue()
        self.profile = profiles[self.golden["profile_id"]]

    def provider(self, *, identity_bound: bool):
        return local.LocalSemanticShadowProvider(
            self.golden["binding_id"],
            self.profile,
            pat_device_id=self.golden["pat_device_id"] if identity_bound else None,
            now=lambda: NOW,
        )

    def ingest(self, provider, schema: str) -> None:
        for publication in self.golden[schema]:
            topic = (
                provider.state_topic
                if publication["topic"].startswith("state/")
                else provider.availability_topic
            )
            payload = json.dumps(publication["payload"], separators=(",", ":")).encode()
            provider.ingest(topic, payload, qos=1, retained=True)

    def expected_state(self, schema: str) -> dict:
        return next(
            publication["payload"]
            for publication in self.golden[schema]
            if publication["topic"].startswith("state/")
        )

    def test_accepts_every_schema_the_publisher_can_emit(self) -> None:
        for schema, identity_bound in (("v1", False), ("v2", True), ("v3", True)):
            with self.subTest(schema=schema):
                provider = self.provider(identity_bound=identity_bound)
                self.ingest(provider, schema)
                published = self.expected_state(schema)["fields"]
                self.assertEqual(
                    set(provider.shadow_fields),
                    set(published),
                    "every field the publisher sent must be visible here",
                )
                for semantic_id, field in published.items():
                    self.assertEqual(
                        provider.field_value(semantic_id),
                        field["value"],
                        f"{semantic_id} decoded to a different value than was published",
                    )
                self.assertEqual(
                    provider.sequence,
                    self.expected_state(schema)["sequence"],
                    "the accepted snapshot must be the one the publisher sent",
                )
                # The availability marker is only accepted when its session matches
                # the snapshot's, so a session here proves the pair went through.
                # `shadow_healthy` additionally needs the runtime marker, which the
                # state feed does not publish and this golden does not carry.
                self.assertEqual(
                    provider.session_id, self.expected_state(schema)["session_id"]
                )

    def test_the_availability_marker_belongs_to_the_snapshot_it_arrived_with(self) -> None:
        # The publisher pairs them; a broker replaying half a stale retained set
        # would otherwise report a device online against state it never described.
        for schema in ("v2", "v3"):
            with self.subTest(schema=schema):
                provider = self.provider(identity_bound=True)
                for publication in self.golden[schema]:
                    payload = dict(publication["payload"])
                    topic = provider.state_topic
                    if not publication["topic"].startswith("state/"):
                        topic = provider.availability_topic
                        payload["state_sequence"] = payload["state_sequence"] + 1
                    encoded = json.dumps(payload, separators=(",", ":")).encode()
                    if topic == provider.state_topic:
                        provider.ingest(topic, encoded, qos=1, retained=True)
                    else:
                        with self.assertRaises(local.LocalProviderContractError):
                            provider.ingest(topic, encoded, qos=1, retained=True)

    def test_an_identity_bound_publication_is_refused_for_another_appliance(self) -> None:
        provider = local.LocalSemanticShadowProvider(
            self.golden["binding_id"],
            self.profile,
            pat_device_id="1" * 64,
            now=lambda: NOW,
        )
        with self.assertRaises(local.LocalProviderContractError):
            self.ingest(provider, "v2")

    def test_the_golden_matches_the_publisher_checkout_when_present(self) -> None:
        if not SIBLING_GOLDEN.exists():
            self.skipTest("sibling lg_rethink_local checkout is not present")
        self.assertEqual(
            GOLDEN_PATH.read_text(encoding="utf8"),
            SIBLING_GOLDEN.read_text(encoding="utf8"),
            "regenerate the golden in the publisher and copy it here in the same change",
        )


if __name__ == "__main__":
    unittest.main()
